spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tdf?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 55990410
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.example.springaopdemo.Entity